INSERT INTO HOTELS (ID, NAME, ADDRESS) VALUES (1, 'Hilton', 'Moscow');

INSERT INTO ROOMS (ID, HOTEL_ID, NUMBER, AVAILABLE, TIMES_BOOKED)
VALUES (1, 1, '101', TRUE, 0);

INSERT INTO ROOMS (ID, HOTEL_ID, NUMBER, AVAILABLE, TIMES_BOOKED)
VALUES (2, 1, '102', TRUE, 0);
